### ISSUE TITLE
White screen on webview in generated apk

### ISSUE THREAD

**Issue by deepaksingh16** [reggie3/react-native-webview-braintree#5]
Hi, 
Braintree webview works fine when running app using react-native command but a white screen appears on using it in generated apk. This would probably be the issue that we might need to put some JS files inside our android and ios projects. Can you explain on what should be included in ios and android projects in order to run this?

**Comment by reggie3** [comment]
This could be an issue that has recently popped up due to react-native webviews.  Are you still seeing the Braintree components, but the other components that are on the screen are not visible because they are covered in white?  If so, I just published version 0.0.5 that should fix it.

**Comment by deepaksingh16** [comment]
Hi @reggie3 Thanks for the solution. Due to time constraint, I had to integrate Native module for payments in my project, but I'll surely checkout new version of this library and will provide feedback.

**Comment by reggie3** [comment]
No problem.  Good luck.
